#!/bin/bash

echo "Configuring database connection and admin password from enviromnent"
./cb_config boss.config boss.config

echo "Starting Chicago Boss application on port $PORT"
#exec erl +K true +P 32768 -pa /app/deps/*/ebin -pa /app/deps/elixir/lib/*/ebin -pa /app/ebin -noshell -boot start_sasl -config boss -s boss
exec erl +K true +P 32768 -pa ../ChicagoBoss/ebin -pa ../ChicagoBoss/deps/*/ebin -pa ../ChicagoBoss/deps/elixir/lib/*/ebin -pa ../${appname}/ebin -pa deps/*/ebin -pa /deps/elixir/lib/*/ebin -noshell -boot start_sasl -config boss -s boss

